### Sudoku Mínimo
np.array([
        [0, 0, 0, 8, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 4, 3, 0],
        [5, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 7, 0, 8, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 2, 0, 0, 3, 0, 0, 0, 0],
        [6, 0, 0, 0, 0, 0, 0, 7, 5],
        [0, 0, 3, 4, 0, 0, 0, 0, 0],
        [0, 0, 0, 2, 0, 0, 6, 0, 0]
    ], dtype=int)
### Sudoku Experto - 
np.array([
        [0, 0, 0, 0, 5, 0, 0, 4, 9],
        [4, 0, 0, 0, 0, 6, 0, 0, 1],
        [0, 0, 1, 0, 0, 3, 0, 5, 0],
        [0, 0, 0, 0, 0, 8, 4, 0, 0],
        [0, 0, 7, 0, 4, 0, 0, 0, 0],
        [0, 2, 0, 1, 9, 0, 0, 8, 0],
        [0, 0, 9, 0, 0, 0, 0, 3, 0],
        [6, 0, 0, 0, 3, 4, 0, 0, 0],
        [3, 0, 0, 0, 0, 0, 7, 0, 0]
    ], dtype=int)
### Sudoku Intermedio
np.array([
        [9, 2, 8, 0, 7, 0, 5, 0, 0],
        [0, 0, 0, 0, 0, 2, 3, 0, 0],
        [0, 6, 0, 0, 0, 0, 0, 2, 9],
        [0, 0, 7, 0, 9, 6, 0, 3, 0],
        [0, 0, 0, 0, 1, 8, 0, 4, 0],
        [2, 0, 0, 0, 0, 3, 0, 0, 6],
        [6, 7, 0, 0, 0, 1, 0, 0, 0],
        [0, 4, 0, 0, 2, 7, 0, 0, 0],
        [8, 0, 1, 0, 4, 0, 2, 0, 0]
    ], dtype=int)
### Sudoku Facil
np.array([
        [0, 0, 0, 4, 0, 0, 7, 0, 0],
        [8, 0, 7, 0, 0, 6, 0, 0, 0],
        [0, 6, 2, 0, 0, 0, 0, 1, 8],
        [0, 0, 0, 3, 0, 1, 8, 9, 0],
        [3, 0, 0, 6, 0, 0, 0, 4, 7],
        [0, 2, 0, 0, 0, 8, 0, 0, 0],
        [9, 0, 8, 0, 6, 3, 1, 5, 4],
        [2, 4, 3, 0, 7, 5, 6, 8, 0],
        [0, 1, 0, 0, 9, 4, 0, 0, 0]
    ], dtype=int)


In [1]:
import numpy as np
from SudokuLibrary.sudoku import Sudoku
from SudokuLibrary.sudokuRestrictions import Sudoku as SudokuRestricted
from SudokuLibrary.sudokuSolver import SudokuSolver
from SudokuLibrary.sudokuSolver import show_sudoku
sudoku = Sudoku(np.array([
        [9, 2, 8, 0, 7, 0, 5, 0, 0],
        [0, 0, 0, 0, 0, 2, 3, 0, 0],
        [0, 6, 0, 0, 0, 0, 0, 2, 9],
        [0, 0, 7, 0, 9, 6, 0, 3, 0],
        [0, 0, 0, 0, 1, 8, 0, 4, 0],
        [2, 0, 0, 0, 0, 3, 0, 0, 6],
        [6, 7, 0, 0, 0, 1, 0, 0, 0],
        [0, 4, 0, 0, 2, 7, 0, 0, 0],
        [8, 0, 1, 0, 4, 0, 2, 0, 0]
    ], dtype=int),
        debug=True)
solver = SudokuSolver(sudoku)

In [2]:
# show_sudoku(solver.sudoku)

In [3]:
sudaka = Sudoku(np.array([
        [9, 2, 8, 0, 7, 0, 5, 0, 0],
        [0, 0, 0, 0, 0, 2, 3, 0, 0],
        [0, 6, 0, 0, 0, 0, 0, 2, 9],
        [0, 0, 7, 0, 9, 6, 0, 3, 0],
        [0, 0, 0, 0, 1, 8, 0, 4, 0],
        [2, 0, 0, 0, 0, 3, 0, 0, 6],
        [6, 7, 0, 0, 0, 1, 0, 0, 0],
        [0, 4, 0, 0, 2, 7, 0, 0, 0],
        [8, 0, 1, 0, 4, 0, 2, 0, 0]
    ], dtype=int),
        debug=True)
sudaka.board_valids = np.zeros((9, 9, 9), dtype=bool)

In [4]:
from itertools import permutations, combinations, product

board = sudoku.board
board_valids = sudaka.board_valids
for irow in range(board_valids.shape[0]):
    for icol in range(board_valids.shape[1]):
        if board[irow, icol] != 0:
            board_valids[irow][icol][board[irow][icol] - 1] = True

for irow in range(board_valids.shape[0]):
    for icol in range(board_valids.shape[1]):
        if np.sum(board_valids[irow, icol]) != 1:
            coords_colision = list(sudaka.get_row_col_cuadrant_coords(irow, icol))
            x, y = zip(*coords_colision)
            valids_per_num_in_colisions = np.sum(board_valids[x, y], axis=0)
            
            board_valids[np.argwhere(valids_per_num_in_colisions == 0).flatten()] = True
a = list(sudoku.get_row_col_cuadrant_coords(1, 0))
x, y = zip(*a)
np.sum(board_valids[x, y], axis=0)
# board_valids[x, y]

array([8, 9, 9, 8, 8, 9, 8, 9, 8])

In [5]:
prueba = np.zeros(9, dtype=bool)
prueba[np.argwhere(np.sum(board_valids[x, y], axis=0) == 0).flatten()] = True
prueba

array([False, False, False, False, False, False, False, False, False])

In [6]:
sudaka = SudokuRestricted(np.array([
        [9, 2, 8, 0, 7, 0, 5, 0, 0],
        [0, 0, 0, 0, 0, 2, 3, 0, 0],
        [0, 6, 0, 0, 0, 0, 0, 2, 9],
        [0, 0, 7, 0, 9, 6, 0, 3, 0],
        [0, 0, 0, 0, 1, 8, 0, 4, 0],
        [2, 0, 0, 0, 0, 3, 0, 0, 6],
        [6, 7, 0, 0, 0, 1, 0, 0, 0],
        [0, 4, 0, 0, 2, 7, 0, 0, 0],
        [8, 0, 1, 0, 4, 0, 2, 0, 0]
    ], dtype=int))
sudaka.valids

array([[False, False, False, False, False, False, False, False,  True],
       [False,  True, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False,  True, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False,  True, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, 

In [7]:
sudaka.basic_restrictions()

In [8]:
for elem in xyz:
    if np.sum(elem[3]) != 1:
        for again in xyz:
            if elem[:3] != again[:3] and (elem[0] == again[0] or elem[1] == again[1] or elem[2] == again[2]):
                elem[3] = np.logical_and(elem[3], np.logical_not(again[3]))
                if np.sum(elem[3]) == 1:
                    print(elem[:3], np.argwhere(elem[3]).flatten())

NameError: name 'xyz' is not defined

In [ ]:
ver = np.zeros((9, 9), dtype=int)
for elem in xyz:
    if np.sum(elem[3]) == 1:
        ver[elem[0], elem[1]] = np.argwhere(elem[3]).flatten()[0] + 1
ver

In [ ]:
show_sudoku(solver.solve_profundidad(True))

In [ ]:
show_sudoku(solver.solve_restricciones(True))

In [ ]:
show_sudoku(solver.solve_anchura(True))

In [ ]:
show_sudoku(solver.solve_coste_uniforme(True))

In [ ]:
show_sudoku(solver.solve_avara(True))

In [ ]:
show_sudoku(solver.solve_a_estrella(True))